### basic settings

# site properties and page defaults
title: UNM Scalable Systems Laboratory
description: A research laboratory at the University of New Mexico specializing in research on large-scale and high performance computing systems.
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""
# /lab-website-template

# site social media and other links
links:
  email: patrickb@unm.edu
  google-scholar: Patrick G. Bridges
  github: UNM-SSL
  #twitter: YourLabHandle
  #instagram: YourLabHandle
  youtube: UNM-SSL

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
